import { BankAccount } from '../types/bank';

/**
 * ============================================================================
 * OFFICIAL BANK ACCOUNTS REPOSITORY
 * F.B Company — شركة إف آند بي لإدارة الأصول
 * ============================================================================
 * 
 * 1. Qatar National Bank (QNB) - بنك قطر الوطني
 * 2. National Bank of Egypt (NBE) - البنك الأهلي المصري (verified from official corporate record)
 * 3. Banque Misr - بنك مصر (verified from official account receipt)
 */

export const OFFICIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'fb-qnb-egp',
    bankName: 'Qatar National Bank (QNB)',
    bankNameArabic: 'بنك قطر الوطني (QNB)',
    bankShortName: 'QNB',
    accountNameEnglish: 'F AND B FOR ASSETS MANAGEMENT',
    accountNameArabic: 'شركة إف آند بي لإدارة الأصول العقارية',
    accountNumber: '20319319586',
    iban: 'EG810037017608182031931958644',
    swift: 'QNBAEGCXXXX',
    branchCode: '00176',
    branchName: 'Corporate Banking Branch',
    branchNameArabic: 'فرع الشركات',
    currency: 'EGP',
    accountType: 'Current Account',
    accountTypeArabic: 'حساب جاري',
    isActive: true,
    displayOrder: 1,
    logoUrl: '/qnb-logo.jpg',
    lastVerifiedAt: '2026-08-18',
    verifiedBy: 'F.B Financial Compliance Division',
    verificationDocRef: 'DOC-QNB-2026-V1',
    notes: 'QNB official corporate receiving account for EGP inbound transfers.'
  },
  {
    id: 'fb-nbe-egp',
    bankName: 'National Bank of Egypt (NBE)',
    bankNameArabic: 'البنك الأهلي المصري',
    bankShortName: 'NBE',
    accountNameEnglish: 'F AND B FOR ASSETS MANAGEMENT',
    accountNameArabic: 'شركة إف آند بي لإدارة الأصول العقارية',
    accountNumber: '1473171709259601015',
    iban: 'EG430003014731717092596010150',
    swift: 'NBEGEGCXXXX',
    currency: 'EGP',
    accountType: 'Corporate Current Account',
    accountTypeArabic: 'حساب شركات جاري',
    isActive: true,
    displayOrder: 2,
    logoUrl: '/nbe-logo.jpg',
    lastVerifiedAt: '2026-08-18',
    verifiedBy: 'F.B Treasury & Banking Operations',
    verificationDocRef: 'DOC-NBE-2026-OFFICIAL',
    notes: 'National Bank of Egypt official verified corporate receiving account.'
  },
  {
    id: 'fb-misr-egp',
    bankName: 'Banque Misr',
    bankNameArabic: 'بنك مصر',
    bankShortName: 'Banque Misr',
    accountNameEnglish: 'F AND B FOR ASSETS MANAGEMENT',
    accountNameArabic: 'شركة إف آند بي لإدارة الأصول العقارية',
    accountNumber: '8420001000005344',
    iban: 'EG180002084208420001000005344',
    swift: 'BMISEGCAXXX',
    branchCode: '842',
    branchName: 'Branch 842',
    branchNameArabic: 'فرع 842',
    currency: 'EGP',
    accountType: 'Current Account',
    accountTypeArabic: 'حساب جاري',
    isActive: true,
    displayOrder: 3,
    logoUrl: '/misr-logo.jpg',
    lastVerifiedAt: '2026-08-18',
    verifiedBy: 'F.B Compliance & Audit Division',
    verificationDocRef: 'DOC-MISR-RCPT-842',
    notes: 'Banque Misr verified from official bank account receipt.'
  }
];

export const BRAND_COLORS = {
  primary: '#003B3C',
  primaryHover: '#002C2D',
  background: '#FFFFFF',
  border: '#E2E8F0',
  secondarySurface: '#F8FAFC',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
};

export const UI_STRINGS = {
  en: {
    portalBadge: 'Official Bank Details',
    companyName: 'F.B Company',
    companySubtitle: 'Assets Management',
    companyNameArabic: 'شركة إف آند بي لإدارة الأصول',
    pageTitle: 'Official Bank Transfer Details',
    pageSubtitle: 'Verified institutional receiving bank accounts for inbound electronic fund transfers.',
    trustBadge: 'Official F.B Company Bank Information',
    verifiedSeal: 'Verified Official Account',
    selectAccount: 'Select Bank Account',
    accountDetails: 'Account Details',
    accountName: 'Account Name (English)',
    accountNameArabicLabel: 'Account Name (Arabic)',
    accountNumber: 'Account Number',
    iban: 'IBAN (International Bank Account Number)',
    swiftBic: 'SWIFT / BIC',
    branchCode: 'Branch Code',
    branchName: 'Branch Name',
    currency: 'Currency',
    accountType: 'Account Type',
    copy: 'Copy',
    copied: 'Copied',
    copyAll: 'Copy All Transfer Details',
    copiedAll: 'All Details Copied',
    toastCopiedField: 'Copied to clipboard',
    toastCopiedAll: 'All transfer details copied to clipboard',
    toastFailed: 'Unable to copy. Please select and copy manually.',
    securityNoticeTitle: 'Security & Verification Notice',
    securityNoticeText: 'For inbound transfers only. F.B Company will never request your banking password, PIN, OTP, or online banking credentials through this portal.',
    securityInboundOnly: 'Inbound Transfers Only',
    footerCompany: 'F.B Company — Asset Management',
    footerRights: 'Official Bank Details Portal. All rights reserved.',
    footerUpdated: 'Last verified records: August 2026',
    shareModalTitle: 'Share Official Bank Portal',
    shareModalSubtitle: 'Scan the QR code or share the permanent URL with clients and partners.',
    copyPortalLink: 'Copy Permanent Portal Link',
    linkCopied: 'Portal link copied',
    close: 'Close',
    activeAccountsCount: 'Active Receiving Banks',
    inboundTransferGuide: 'Transfer Instructions',
    inboundTransferTip: 'Please mention your company name or invoice reference in the transfer memo for prompt reconciliation.',
    qrCodeDesc: 'Permanent URL for NFC cards & QR codes'
  },
  ar: {
    portalBadge: 'بيانات الحسابات البنكية الرسمية',
    companyName: 'شركة إف آند بي لإدارة الأصول',
    companySubtitle: 'F.B Company — Assets Management',
    companyNameArabic: 'شركة إف آند بي لإدارة الأصول العقارية',
    pageTitle: 'بيانات التحويل البنكي الرسمية',
    pageSubtitle: 'الحسابات البنكية المؤسسية المعتمدة لاستقبال التحويلات البنكية الواردة لشركة إف آند بي.',
    trustBadge: 'بيانات بنكية رسمية لشركة F.B',
    verifiedSeal: 'حساب رسمي معتمد وموثق',
    selectAccount: 'اختر الحساب البنكي',
    accountDetails: 'تفاصيل الحساب البنكي',
    accountName: 'اسم الحساب بالإنجليزية',
    accountNameArabicLabel: 'اسم الحساب بالعربية',
    accountNumber: 'رقم الحساب',
    iban: 'رقم الحساب الدولي (IBAN)',
    swiftBic: 'رمز السويفت (SWIFT / BIC)',
    branchCode: 'كود الفرع',
    branchName: 'اسم الفرع',
    currency: 'العملة',
    accountType: 'نوع الحساب',
    copy: 'نسخ',
    copied: 'تم النسخ',
    copyAll: 'نسخ جميع بيانات التحويل',
    copiedAll: 'تم نسخ كافة البيانات',
    toastCopiedField: 'تم النسخ إلى الحافظة بنجاح',
    toastCopiedAll: 'تم نسخ جميع بيانات التحويل بنجاح',
    toastFailed: 'تعذر النسخ تلقائيًا، يرجى التحديد والنسخ يدويًا.',
    securityNoticeTitle: 'تنبيه أمني وإرشادات رسمية',
    securityNoticeText: 'هذه البيانات مخصصة للتحويلات البنكية الواردة فقط. لن تطلب شركة إف آند بي مطلقًا كلمة المرور البنكية، أو الرمز السري PIN، أو رمز OTP، أو أي بيانات دخول بنكية خاصة بك من خلال هذه البوابة.',
    securityInboundOnly: 'للتحويلات البنكية الواردة فقط',
    footerCompany: 'شركة إف آند بي لإدارة الأصول',
    footerRights: 'البوابة الرسمية لبيانات التحويلات البنكية. جميع الحقوق محفوظة.',
    footerUpdated: 'تاريخ التحقق من السجلات: أغسطس 2026',
    shareModalTitle: 'مشاركة البوابة الرسمية',
    shareModalSubtitle: 'امسح رمز الاستجابة السريعة (QR) أو انسخ الرابط الدائم لمشاركته مع العملاء والشركاء.',
    copyPortalLink: 'نسخ الرابط الدائم للبوابة',
    linkCopied: 'تم نسخ رابط البوابة بنجاح',
    close: 'إغلاق',
    activeAccountsCount: 'بنوك معتمدة للاستقبال',
    inboundTransferGuide: 'إرشادات التحويل',
    inboundTransferTip: 'يرجى كتابة اسم الشركة أو رقم الفاتورة في خانة الغرض من التحويل لتسريع المطابقة المالية.',
    qrCodeDesc: 'رابط دائم مخصص لبطاقات NFC ورموز QR'
  }
};
